#include "Wio3GConfig.h"
#include "Wio3GHardware.h"

HardwareSerial SerialUSB(DEBUG_UART_CORE, DEBUG_UART_TX_PIN, DEBUG_UART_RX_PIN);
HardwareSerial SerialModule(MODULE_UART_CORE, MODULE_UART_TX_PIN, MODULE_UART_RX_PIN);

HardwareSerial SerialUART(GROVE_UART_CORE, GROVE_UART_TX_PIN, GROVE_UART_RX_PIN);
TwoWire WireI2C(GROVE_I2C_CORE, GROVE_I2C_SCL_PIN, GROVE_I2C_SDA_PIN);
